# Site settings
title:          dom's experiments & prototyping
description:    "A place to learn, experiment, and prototype interactions"
url:            "https://aekeledo.github.io"

# Author
author:
  name:         Adanma Dom Ekeledo
  url:          https://hello-dom.com
  email:       aekeledo@gmail.com

# Build settings
markdown:       kramdown

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

# Gems
plugins:
  - jekyll-paginate

# Permalinks
permalink:      /:year-:month-:day/:title
paginate:       10
